# Generated by Django 3.1.5 on 2021-02-08 17:23

from django.conf import settings
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('profiles', '0002_auto_20210208_1719'),
    ]

    operations = [
        migrations.AlterUniqueTogether(
            name='following',
            unique_together={('follower', 'victim')},
        ),
    ]
